services:
  a-php:
    container_name: a-php
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../logs:/applogs
    expose:
      - 9000
    environment:
      DATABASE_HOST: mobillett_db
      DATABASE_USERNAME: mobillett
      DATABASE_PASSWORD: FleskBurger
      DATABASE_NAME: mobillett
      SESSION_SAVE_HANDLER: files
      SESSION_SAVE_PATH: /tmp