name: "Test docker"

on:
  push:
    branches:
      - master

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker composer
        run: |
          cd docker
          docker compose up -d

      - name: Run tests in container
        run: |
          docker ps
          docker exec a-php composer install
          docker exec a-php ping -c 4 a_db
          docker exec a-php ping -c 4 a-mysql
          docker exec a-php ping -c 4 mobillett_db
          docker exec a-php ping -c 4 a-mysql.docker_mob
          docker exec a-php php test-pdo.php